package General;

/**
 * Acciones a ser realizadas por el programa
 */
public enum TipoAccion {
    SALUDAR,
    REGISTRAR_PLAYER,
    GET_CANTIDAD_PLAYERS_CONECTADOS,
    ENVIAR_MENSAJE,
    AGREGAR_PANEl_CHAT,
    AGREGAR_ULTIMO_PUNTO,
    AGREGAR_JUGADOR,
    JUGADOR_LISTO,
    ACTUALIZAR_DINERO,
    ELIMINAR_JUGADOR_POR_ITEMS,
    ELIMINAR_JUGADOR_POR_ID,
    ACTUALIZAR_ACERO,
    SET_INVENTARIO_COMBOBOX,
    INSERTAR_ITEM_EN_GRID,
    OBTENER_ULTIMO_PUNTO,
    CONSULTA_CELDA_DISPONIBLE,
    SET_PUNTOS_ITEM,
    ACTUALIZAR_CHAT,
    GET_JUGADOR_POR_ID,
    SET_CAMBIOS_JUGADOR_ITEMS,
    BUSCAR_ITEM_VIVO,
    REALIZAR_COMPRA_ITEM,
    CONSULTAR_CANTIDAD_SUFICIENTE_DINERO,
    VENDER_AL_MERCADO,
    AGREGAR_ULTIMO_CONECTOR,
    GET_ULTIMO_PUNTO_CONECTOR,
    OBTENER_ITEM_POR_PUNTO,
    AGREGAR_ITEM_A_CONECTOR,
    BUSCAR_ITEM_POR_ID,
    SUMAR_ACERO_JUGADOR

}
