package General;

/**
 * Acciones a ser realizadas por el programa
 */
public enum TipoAccion {
    SALUDAR,
    REGISTRAR_PLAYER,
    GET_CANTIDAD_PLAYERS_CONECTADOS,
    ENVIAR_MENSAJE,
    AGREGAR_PANEl_CHAT,
    AGREGAR_ULTIMO_PUNTO,
    AGREGAR_JUGADOR,
    JUGADOR_LISTO,
    ACTUALIZAR_DINERO,
    ELIMINAR_JUGADOR_POR_ITEMS,
    ELIMINAR_JUGADOR_POR_ID,
    ACTUALIZAR_ACERO,
    SET_INVENTARIO_COMBOBOX,
    INSERTAR_ITEM_EN_GRID,
    OBTENER_ULTIMO_PUNTO,
    CONSULTA_CELDA_DISPONIBLE,
    SET_PUNTOS_ITEM
}
